Solution/GemsCafe.Website/ViewModels/ContactViewModel.cs
namespace GemsCafe.Website.ViewModels
{
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using GemsCafe.Website.ViewModels.Base;

    public class ContactViewModel : BaseViewModel
    {
        public string Title { get; set; }
        public string GoogleMapsUrl { get; set; }
        public string Address { get; set; }
        public string FormIntro { get; set; }


        // Properties to support the form
        [Required(ErrorMessage = "Please enter your name")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Please enter an email address")]
        [EmailAddress(ErrorMessage = "Please use a valid email address")]
        [DisplayName("Email Address")]
        public string Email { get; set; }

        [Required(ErrorMessage = "Please enter a message")]
        public string Message { get; set; }

        public bool FormPostSuccess { get; set; }
    }
}

Solution/GemsCafe.Website/Controllers/ContactController.cs
namespace GemsCafe.Website.Controllers
{
    using System.Web.Mvc;
    using DevTrends.MvcDonutCaching;
    using GemsCafe.Website.App;
    using GemsCafe.Website.App.CmsDefinitions;
    using GemsCafe.Website.ViewModels;
    using Umbraco.Web;
    using Umbraco.Web.Models;

    public class ContactController : BaseController
    {
        [DonutOutputCache(CacheProfile = CacheProfiles.SixHours)]
        [HttpGet]
        public override ActionResult Index(RenderModel model)
        {
            var viewModel = CreateViewModel<ContactViewModel>();
            PopulateViewModel(viewModel);
            return CurrentTemplate(viewModel);
        }

        /*
         * The antiforgerytoken is a way of ensuring that the request that is coming to a post action is actually one that originated from your 
         * outputted view. It stops cross site scripting attacks and handles post replay attacks too.
         */
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Contact(ContactViewModel model)
        {
            PopulateViewModel(model);

            if (!ModelState.IsValid)
            {
                return CurrentTemplate(model);
            }

            // 
            // Persist the model to a database or similar here....
            //

            model.FormPostSuccess = true;
            return CurrentTemplate(model);
        }

        private void PopulateViewModel(ContactViewModel viewModel)
        {
            viewModel.Title = CurrentPage.GetPropertyValue<string>(ContactDoctype.Fields.Title);
            viewModel.GoogleMapsUrl = CurrentPage.GetPropertyValue<string>(ContactDoctype.Fields.GoogleMapsUrl);
            viewModel.Address = CurrentPage.GetPropertyValue<string>(ContactDoctype.Fields.Address);
            viewModel.FormIntro = CurrentPage.GetPropertyValue<string>(ContactDoctype.Fields.FormIntro);
        }
    }
}

Solution/GemsCafe.Website/Controllers/Surface/ComponentsController.cs
namespace GemsCafe.Website.Controllers.Surface
{
    using System.Web.Mvc;
    using GemsCafe.Website.App;
    using GemsCafe.Website.App.CmsDefinitions;
    using GemsCafe.Website.App.Models;
    using GemsCafe.Website.ViewModels.Components;
    using Umbraco.Web;
    using Umbraco.Web.Mvc;

    public class ComponentsController : SurfaceController
    {
        /*
         * For info - [ChildActionOnly] shouldn't be used with [HttpGet]. 
         * The reason is because when you mark an action with [ChildActionOnly] you are telling MVC to make this not publicly 
         * routable (i.e. it doesn't have a URL) and can only be rendered using Html.Action so applying [HttpGet] is irrelavent.
         */

        [ChildActionOnly]
        public ActionResult TopNavigation()
        {
            var queryService = new QueryService(Umbraco);
            var model = new TopNavigationViewModel();

            // Add home node
            var rootNode = queryService.GetRoot();
            model.NavigationItems.Add(new NavigationItem
            {
                Title = rootNode.Name,
                Url = rootNode.Url
            });

            // Add nodes at first level that havent been hidden using umbracoNaviHide
            foreach (var firstLevelNode in queryService.GetFirstLevelNodes())
            {
                // Check the node isnt hidden from nav
                if (!firstLevelNode.IsVisible()) continue;

                model.NavigationItems.Add(new NavigationItem
                {
                    Title = firstLevelNode.Name,
                    Url = firstLevelNode.Url
                });
            }

            return PartialView(model);
        }

        [ChildActionOnly]
        public ActionResult Header()
        {
            var model = new HeaderViewModel();
            model.Title = CurrentPage.GetPropertyValue<string>(PageDoctype.Fields.HeaderTitle, true);
            model.Address = CurrentPage.GetPropertyValue<string>(PageDoctype.Fields.HeaderAddress, true);
            return PartialView(model);
        }

        [ChildActionOnly]
        public ActionResult Footer()
        {
            var model = new FooterViewModel();
            model.Text = CurrentPage.GetPropertyValue<string>(PageDoctype.Fields.FooterText, true);
            return PartialView(model);
        }
    }
}

Solution/GemsCafe.Website/Views/Shared/_ContactForm.cshtml
@model GemsCafe.Website.ViewModels.ContactViewModel

<p>@Model.FormIntro</p>
@using (Html.BeginForm("Contact", "Contact"))
{
    @Html.AntiForgeryToken()
    <div class="row">
        <div class="col-lg-12">
            @Html.ValidationSummary()
        </div>
    </div>
    <div class="row">
        <div class="form-group col-lg-6">
            @Html.LabelFor(x => x.Name)
            @Html.TextBoxFor(x => x.Name, new { @class = "form-control" })
        </div>
        <div class="form-group col-lg-6">
            @Html.LabelFor(x => x.Email)
            @Html.TextBoxFor(x => x.Email, new { @class = "form-control" })
        </div>
        <div class="clearfix"></div>
        <div class="form-group col-lg-12">
            @Html.LabelFor(x => x.Message)
            @Html.TextAreaFor(x => x.Message, new { @class = "form-control", rows = 6 })
        </div>
        <div class="form-group col-lg-12">
            <button type="submit" class="btn btn-default">Submit</button>
        </div>
    </div>
}

Solution/GemsCafe.Website/Views/Shared/_ContactFormThanks.cshtml
@model GemsCafe.Website.ViewModels.ContactViewModel

<div class="row">
    <div class="col-lg-12">
        <div class="alert alert-success">
            <strong>Thanks for your message.</strong> We'll be in back in touch as soon as possible.
        </div>
    </div>
</div>

Solution/GemsCafe.Website/Views/Shared/_MainLayout.cshtml
@model GemsCafe.Website.ViewModels.Base.IBaseViewModel
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@Model.PageTitle</title>
    <meta name="description" content="@Model.PageDescription">
    <link href="/css/bootstrap.css" rel="stylesheet">
    <link href="/css/business-casual.css" rel="stylesheet">
    @RenderSection("Head", false)
</head>

<body>
    <!--The server constructed this page at: @Model.PageConstructedAt -->

    @Html.Action("Header", "Components")
    @Html.Action("TopNavigation", "Components")

    <div class="container"> 
        @RenderBody()
    </div>
    
    @Html.Action("Footer", "Components")

    <script src="/js/jquery-1.10.2.js"></script>
    <script src="/js/bootstrap.js"></script>
    @RenderSection("JsFooter", false)
    
</body>
</html>